In [1]:
#pyotch is just numpy running on GPU with nice helper fucntions
#CPU was designed for large and big calculations but small in number
#GPU was designed for small but lot of calculations - thats why it's helpful in deep-learning

In [4]:
import torch

x=torch.tensor([5,3])
y=torch.tensor([2,1])
x*y

tensor([10,  3])

In [5]:
x=torch.zeros([2,5])

In [6]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [7]:
x.shape

torch.Size([2, 5])

In [8]:
y=torch.rand([2,6])
y

tensor([[0.3582, 0.8846, 0.8019, 0.1768, 0.8538, 0.3789],
        [0.5075, 0.1159, 0.5577, 0.2863, 0.7735, 0.3720]])

In [9]:
#in pytoch instaed of .reshape we have .view
y.view([1,12]) # this is not an in-place operation so you would have to assign it new variable

tensor([[0.3582, 0.8846, 0.8019, 0.1768, 0.8538, 0.3789, 0.5075, 0.1159, 0.5577,
         0.2863, 0.7735, 0.3720]])

In [10]:
y

tensor([[0.3582, 0.8846, 0.8019, 0.1768, 0.8538, 0.3789],
        [0.5075, 0.1159, 0.5577, 0.2863, 0.7735, 0.3720]])